# Generated by Django 5.0.6 on 2024-07-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_organisation_user_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organisation',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Organisation',
        ),
    ]
